config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
   
  resources :pet_policies
  resources :dogs
  resources :renter_apartment_applications
  resources :apartments
  resources :renters
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
    has_many :renter_apartment_applications
    has_many :renters, through: :renter_apartment_applications
    has_one :pet_policy

    # def self.find_by_restrictions(rent_allowance)
    #     rent =  Apartment.where(“rent_allowance > ? “, rent_allowance)
    #         rent.map do |p|
    #         p.apartment
    #         end
    # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :renter
end

app/models/pet_policy.rb
class PetPolicy < ApplicationRecord
  belongs_to :apartment


  # def self.find_by_restrictions(weight, breed)
  # found_policies =  PetPolicy.where("weight_max > ? AND NOT breed_restriction = ?", weight, breed)

  #   found_policies.map do |p|
  #     p.apartment
  #   end

  # end



end

app/models/renter.rb
class Renter < ApplicationRecord
    has_many :renter_apartment_applications
    has_many :apartments, through: :renter_apartment_applications
    has_one :dog
end

app/models/renter_apartment_application.rb
class RenterApartmentApplication < ApplicationRecord
  belongs_to :renter
  belongs_to :apartment
  
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
    
    def index
        @apartments = Apartment.all
    end

    def show
        @apartment = Apartment.find(params[:id])
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    
    def new
        @dog = Dog.new
        @renters = Renter.all
    end

    def create
        dog = Dog.create(dog_params)
        redirect_to dog_path(dog)
    end

    def edit  
        @dog = Dog.find(params[:id])
    end

    def update
        dog = Dog.find(params[:id])
        dog_params
    end

    def show
        @dog = Dog.find(params[:id])
    end
    
    private

    def dog_params
        params.require(:dog).permit(:name, :weight, :breed, :bio, :renter_id)
    end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
    
  end

app/controllers/pet_policies_controller.rb
class PetPoliciesController < ApplicationController

    def index
        @pet_policies = PetPolicy.all
    end

       
end

app/controllers/renter_apartment_applications_controller.rb
class RenterApartmentApplicationsController < ApplicationController
    
    def new
        @renter_apartment_application = RenterApartmentApplication.new
        @renters = Renter.all
        @apartments = Apartment.all
    end

    def create
        renter_apartment_application = RenterApartmentApplication.create(renter_apartment_application_params)
        redirect_to apartments_path
    end

    private

    def renter_apartment_application_params
        params.require(:renter_apartment_application).permit(:renter_id, :apartment_id, :email)
    end 



end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
   
    
    def new
        @renter = Renter.new
    end

    def create
        renter = Renter.create(renter_params)
        redirect_to renter_path(renter)
    end

    def edit  
        @renter = Renter.find(params[:id])
    end

    def update
        renter = Renter.find(params[:id])
        renter_params
        redirect_to renter_path(renter)
    end
    
    def show
        @renter = Renter.find(params[:id])
    end
    
    def destroy
        renter = Renter.find(params[:id])
        renter.destroy
        redirect_to root_url
    end

    private

    def renter_params
        params.require(:renter).permit(:name, :rent_allowance)
    end


end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pet_policies_helper.rb
module PetPoliciesHelper
end

app/helpers/renter_apartment_applications_helper.rb
module RenterApartmentApplicationsHelper
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/views/apartments/index.html.erb
<center><h1>Available Pet Friendly Apartments</h1>
<main>
<br>
<ul>
  <% @apartments.each do |apartment| %>
    <p> <%= link_to apartment.address, apartment %> </p>
  <% end %>
</ul>

</main>

<br>
<nav> 
<%= link_to "Go Back", "/", class: "btn btn-danger" %>
</nav>
</center>

app/views/apartments/show.html.erb
<center>
    <h1>Apartment Information</h1>
    <br>
    <img class="fit-picture"
    style="width: 30%"
     src=https://images.pexels.com/photos/2434202/pexels-photo-2434202.jpeg?cs=srgb&dl=pexels-bhargava-marripati-2434202.jpg&fm=jpg
     alt="Downtown Chicago skyline at sunset with a pink and blue sky"
     align="center">
     <br>
    <textarea rows="5" cols="60" wrap="hard">Description:<%= @apartment.description %></textarea>
    <br>
    <b><p>Address: <%= @apartment.address %></p></b>
    <br>


    <h2>Pet Policy</h2>
    <br>
    <p>Breed Restrictions:<%= @apartment.pet_policy.breed_restriction %></p>
    <br>
    <p>Maximum Weight:<%= @apartment.pet_policy.weight_max %></p>
    <br>


    <nav>
    <p><%= link_to 'Back to Apartments', apartments_path, class: "btn btn-danger"%></p>
    <%= link_to "Apply Now!", new_renter_apartment_application_path, class: "btn btn-danger" %> 
    </nav>

</center>

app/views/dogs/new.html.erb
<center><h1>Create Your Dog's Profile</h1>
<main>

<img class="fit-picture"
    style="width: 15%"
     src=https://images.pexels.com/photos/5122188/pexels-photo-5122188.jpeg?cs=srgb&dl=pexels-nataliya-vaitkevich-5122188.jpg&fm=jpg
     alt="Corgi smiling in front of a laptop"
     align="center">
    

<DIV align="center">
<%= form_for @dog do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.label :weight %>: lbs</p>
<p><%= f.text_field :weight %></p>
<p><%= f.label :breed %></p>
<p><%= f.collection_select :breed, Dog.all, :id, :breed %></p>
<p><%= f.label :bio %></p>
<p><%= f.text_field :bio %></p>
<p><%= f.label :renter_id %></p>
<p><%= f.collection_select :renter_id, @renters, :id, :name %></p>
<br>
<%= f.submit %>
<% end %>
</DIV>
</main>
</center>

app/views/dogs/show.html.erb
<center><h1> Your Dog Profile </h1>
<br>
 <img class="fit-picture"
    style="width: 30%"
     src=https://images.pexels.com/photos/5256707/pexels-photo-5256707.jpeg?cs=srgb&dl=pexels-samson-katt-5256707.jpg&fm=jpg
     alt="A pair of white dog paws hold open a book. A pair of glasses sit on top of the open pages"
     align="center">
<br>
<main>

<b><p>Name: <%= @dog.name %></p></b>
<p>Weight: <%= @dog.weight %>lbs</p>
<p>Breed: <%= @dog.breed %></p>
<p>Pawrent: <%= @dog.renter.name %></p>
<p>Bio: <%= @dog.bio %></p>

</main>


<br>
<br>
<nav>
<%= link_to 'Back to Renter Profile', renter_path(@dog.renter), class: "btn btn-danger" %>
</nav>



</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogHouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<center><h1> Welcome to Doghouse </h1>
<br>

<img class="fit-picture"
    style= "width: 35%" 
     src="https://images.pexels.com/photos/3987557/pexels-photo-3987557.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
     alt="brown-short-coated-dog-sitting-inside-open-doorway-behind-welcome-matt">
<br>
<p>We help dog owners find pet-friendly apartments within thier budget! </p>
<br>

<nav>
 <%= link_to "Wipe Your Paws Please", new_renter_path, class: "btn btn-danger" %> 
</nav>

</center>

app/views/renter_apartment_applications/new.html.erb
<center><h1> Apply Now:</h1>

<main>
<%= form_for @renter_apartment_application do |f| %>
<p><%= f.label :renter_id %></p>
<p><%= f.collection_select :renter_id, Renter.all, :id, :name %></p>
<br>
<p><%= f.label :apartment_id %>
<p><%= f.collection_select :apartment_id, Apartment.all, :id, :address %></p>
<br>
<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>
<br>
<p><%= f.submit %></p>

<% end %>

</main>

</center>

app/views/renters/edit.html.erb
<center><h1> Update Your Information </h1>
<br>
<main>
<img class="fit-picture"
    style= "width: 35%" 
     src="https://images.pexels.com/photos/1181511/pexels-photo-1181511.jpeg?cs=srgb&dl=pexels-christina-morillo-1181511.jpg&fm=jpg"
     alt="hands-typing-on-a-keyboard">
<br>     
<br>
<%= form_for @renter  do |form_helper|%>

    <%= form_helper.label :name %>
    <br>
        <%= form_helper.text_field :name %>
    <br>
    <br>
    <%= form_helper.label :rent_allowance %>
    <br>
    <%= form_helper.text_field :rent_allowance %>
    <br>
    <br>
    <%= form_helper.submit "Submit Changes" %> 
<% end %>
</main>
<br>
<nav>
<%= link_to 'Back to Renter Profile', renter_path(@renter), class: "btn btn-danger" %>
</nav>
</center>

app/views/renters/new.html.erb
<center>

<h1>Create a Renter Profile:</h1>
<br>
<img class="fit-picture"
    style= "width: 35%" 
     src="https://images.pexels.com/photos/2030037/pexels-photo-2030037.jpeg?cs=srgb&dl=pexels-naim-benjelloun-2030037.jpg&fm=jpg"
     alt="hands-typing-on-a-keyboard">
     <br>

<i><b><p> We just need some starter information to set up your renter profile:<p></b></i>

<main>
<%= form_for @renter do |f| %>
<p><%= f.label :name  %>:</p>
<p><%= f.text_field :name %></p>
<br>
<p><%= f.label :rent_allowance %>:</p>
<p><%= f.text_field :rent_allowance %></p>
<br>
<%= f.submit %>
<% end %>

</main>

</center>

app/views/renters/show.html.erb
<center>
<h1><%=@renter.name%>'s Profile </h1>
<br>
<main>

<img class="fit-picture"
    style= "width: 40%" 
     src="https://images.pexels.com/photos/5256147/pexels-photo-5256147.jpeg?cs=srgb&dl=pexels-samson-katt-5256147.jpg&fm=jpg"
     alt="woman-sitting-at-a-table-working-on-a-laptop-with-her-scruffy-tan-colored-dog-sitting-in-the-other-chair">

<b><p>Name: <%= @renter.name %></p></b>
<b><p>Rent Allowance: $<%= @renter.rent_allowance %></p></b>

</main>

<nav>
<p> <%= link_to "Create Dog Profile", new_dog_path, class: "btn btn-danger" %> </p>
<br>
<p> <%= link_to "Update Renter Info", edit_renter_path, class: "btn btn-danger" %> </p>
<br>
<p> <%= link_to "See Apartment Listings", apartments_path, class: "btn btn-danger" %> </p>
<br>
</nav>

<p><%= button_to "Delete Profile", @renter, :method => :delete, class: "btn btn-danger" %></p>

</center>